project:
  type: website
  output-dir: docs

website:
  title: "Andrew Gard, Ph.D"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  favicon: assets/logo_transparent.png
  navbar:
    logo: assets/logo_beige.png
    background: "#5798A6"
    left:
      - text: Equitable Equations
        href: ee.qmd
      - text: Normal Knowledge
        href: nk.qmd
      - text: Consulting
        href: consulting.qmd
      - text: CV
        menu:
          - text: Narrative
            href: cv.qmd
          - text: Formal
            href: cv_formal.qmd
          
  
  page-footer:
    border: true
    left: "&#169; 2025 Andrew Gard"
    center:  
      - text: License
        href: license.qmd
      - text: About this site
        href: about.qmd
      - text: CoC
        href: coc.qmd
      - text: Accessibility
        href: accessibility.qmd
      - text: Giving
        href: giving.qmd
    right: "made with ︎♥️ & [Quarto](https://quarto.org)"      
        
        
format:
  html:
    theme: [cosmo, styles.scss]
    smooth-scroll: true
    link-external-newwindow: true

