---
title: "How to YouTube: lessons I learned the hard way"
---

While all you really need to start a channel is a computer (or even just a phone), some upgrades can make a huge difference. 

- **Microphone**: A decent microphone is the first purchase you should make when you start to get serious about your YouTube channel (or your podcast, TikTok account, or whatever). Nothing makes a viewer click away faster than poor sound quality. I currently use a Shure MV-7, but also had great results with a Rode NT-USB mini (only about $100!). A boom arm with shock mount is a good low-cost add-on. 

- **Video sizing**: YouTube strongly prefers an aspect ratio of 16:9, though the screen on MacBooks (like my Air) is 16:10. In order to make everything match up, I use SwitchResX to force my Mac into the necessary resolution before recording my screen. 

- **Recording and editing**: I used OBS Studio (which is free) without complaints for my first two years, but Camtasia was a huge quality of life upgrade. It records my face, screen, and audio on separate tracks, then provides user-friendly tools for editing and combining the various elements. I keep recording when I get tongue-tied now, backing up only to the start of my thought and then deleting the embarrassing stuff later on, usually with a smooth fade from one clip to the other.

- **Logo and thumbnails**: Anyone will tell you that quality thumbnails are absolutely essential for attracting viewers. If you're just starting out, I recommend starting with a template like those offered by Adobe, Canva, and many others. After my channel monetized, I contracted a designer (Tiara Wiggins at Twiggs Creative) to professionalize my channel. I strongly recommend an experienced human over AI or DIY options. 

- **Intro and end screens**: Canva offers free tools for animating images. I started with my logo, then wiped it in and out. With a little tinkering, you can probably do even better. I think the results are pretty good, but will ultimately bring in professional help to improve this, too. 

- **Slides**: I'm old school, for better and for worse. Usually my slides are made with LaTeX, which reflects my background in pure mathematics. I also occasionally use PowerPoint and Quarto. None of these are especially engaging, I'm sure, but they're what I know and they're at least appropriate to material that I cover. 

- **Graphics**: My data-oriented visualizations are made in R, usually with `ggplot2`, while more algebraic plots (like density curves) are generally done in Geogebra. All of this is free. 

There's a lot more to YouTube than just hitting "record" and talking to the camera. It's been a long learning curve for me, and I hope yours will be shorter. Feel free to message me on LinkedIn if you have questions!


