---
title: "Why haven't I covered tidymodels?"
author:
  - name: Andrew Gard
date: 08-04-2026
categories: [tidymodels] 
draft: true 
comments:
  utterances:
    repo: equitable-equations/website
---

I get this question from time to time, and with good reason. The `tidymodels` framework for data modeling is powerful and about as user-friendly as we can hope for in this space, bringing consistency and clarity to a process that can continue to feel ad-hoc well into the learning curve. Over time, it's supplanted the older favorite meta-package, `carat`, which coincidentally (note sarcasm) was written by one the primary `tidymodels` architects, Max Kuhn.

I love `tidymodels` and use it consistently for my machine learning needs. Yet when I've done vids on ML techniques, I've almost always shied away, opting to use individual packages instead. Why?

The short answer is that I haven't figured out how to teach it in a YouTube-friendly way yet. Vids on Equitable Equations aim to be short, self-contained, clear expositions of individual topics. While these can (and should!) be chained together to build a comprehensive whole, it's important to me - and to the Almighty Algorithm, whom we all serve - that they stand on their own. Machine learning is hard to do this way. 

One of the wonderful things about the core `tidyverse` is the degree to which it teaches basic data science concepts. When we learn `ggplot2`, we learn the grammar of graphics. When we learn `tidyr`, we learn about tidy data and pivoting. As we move deeper into the era of automated coding, this structure for gaining conceptual knowledge (which we can outsource to AI only if we resign ourselves to irrelevance) is invaluable. 

But `tidymodels` isn't like this. It's a higher-order system designed to unify a large number of related tasks, some of which have very little meaning outside of a machine learning workflow. 

If you're sitting down to study logistic regression for the first time, for instance, `tidymodels` will simultaneously want you to consider a data split, preprocessing steps, and performance metrics, to start. This is wonderful and important, ultimately, but puts a huge burden on the learner, not to mention the YouTuber. 

I tried `tidymodels` when I first began studying machine learning but quickly gave it up in favor of simpler (though objectively worse) tools in base R. I suspect this experience is close to universal. Conceptual knowledge makes these tools tractable, not the other way around. 

Over time, I've covered many components of the ML process in my vids, keeping them as separate and simple as possible. This has often come at the expense of data science best practices, for instance when I build models without first splitting data or concluding by computing performance metrics. 




